# Header
menu:
  Home: /
  Archives: /archives
  Github:
    url: https://github.com/user
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title:

# Intro
intro_title:  #This is the title of the Jumbotron
intro_lead:   #This is the text that appears under the title, which is larger than normal text
intro_text:   #This appears below the title and lead, and appears like normal text.
intro_btn_caption:  #This is the text that appears on the button under the intro_text.
intro_btn_link:  #This is the link that activates when the button is clicked.

# URL of the Home page image
index_cover: flat-2833953_1280.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Addthis ID
addthis:

# set your own favicon
favicon:

# Social Accounts
twitter_url: https://twitter.com/user
twitter_handle:
facebook_url:
github_url: https://github.com/user
gitlab_url:
linkedin_url:
mailto:

# Node sass Config
# see https://github.com/sass/node-sass
node_sass:
  outputStyle: nested
  precision: 4
  sourceComments: false