# Header
menu:
  Home: /
  Archives: /archives
  Github:
    url: https://github.com/houfu
    icon: github
  LinkedIn:
    url: https://www.linkedin.com/in/hou-fu-ang-0a6851113/
    icon: linkedin


# Title on top left of menu. Leave empty to use main blog title
menu_title:

# Intro
intro_title:
intro_lead:
intro_text:

# URL of the Home page image
index_cover: flat-2833953_1280.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: this-is-houfu
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Addthis ID
addthis: ra-5ae499595f194cac

# set your own favicon
favicon:

# Social Accounts
twitter_url: https://twitter.com/houfu
twitter_handle: houfu
facebook_url:
github_url: https://github.com/houfu
gitlab_url:
linkedin_url: https://www.linkedin.com/in/hou-fu-ang-0a6851113/
mailto: damon.houf@gmail.com

# Node sass Config
# see https://github.com/sass/node-sass
node_sass:
  outputStyle: nested
  precision: 4
  sourceComments: false